Render negative times
rianadon/timer-bar-card pull request #148
Opened 2024-04-25 21:31 UTC by SLaks

This is particularly important for timers like Google Home that don'stay while ringing until explicitly dismissed; this lets me see how long the timer was ringing for.

I did not verify that all of the rounding behaves correctly.

2024-04-26 02:57 UTC, rianadon commented
Interesting! I hadn't even noticed, but you snuck in the ability to render negative times with the `state: { fixed }`. Thanks for fixing up this hidden feature.

I took a look at the rounding and it is inconsistent. `h`, `m`, and `s` all round down to smaller magnitude times. Meanwhile, `hms` and `hm` round up. I think rounding down here is the correct behavior, so that if you're rounding a timer that's run 1 second over to the nearest hour, you get a `0` instead of the timer immediately jumping to `-1` once it's finished.

In terms of implementation, you should be able to leave the `hmsTime` and `hmTime` alone, and instead patch `joinWithColons` to handle the negatives.

2024-04-26 02:58 UTC, rianadon commented on test/format-time.test.ts
> +    expect(formatTime(-d, 'hm')).toBe('-2:47')
```suggestion
    expect(formatTime(-d, 'hm')).toBe('-2:46')
```

2024-04-26 02:59 UTC, rianadon requested changes
This is how I'd expect the rounding to be in the tests.

2024-04-26 02:59 UTC, rianadon commented on test/format-time.test.ts
> +    expect(formatTime(-d, 'hm')).toBe('-2')
```suggestion
    expect(formatTime(-d, 'hm')).toBe('-1')
```

2024-04-30 00:05 UTC, rianadon reviewed
It looks like you're rounding the seconds and minutes in opposite directions. I made some suggestions on how I was hoping this worked. Primarily, I'm trying to avoid the timer jumping past zeros (ideally a timer slightly above zero will show `1hr`, but slightly below zero will show `0hr`). This also shouldn't require changing any of the rounding (`ceil`/`floor`) logic.

This is what makes sense in my head, but I'm happy to hear your reasons for always rounding away from zero if that's what makes more sense in your head.

2024-05-05 17:06 UTC, SLaks commented
Ah; I see what you mean now.

How's this?

I noticed some more issues and added more test coverage.

2024-05-05 18:03 UTC, rianadon commented
Looks perfect! Thanks so much for bearing with all the reviews and adding those additional tests.

Things are busy this week but I'll try to get a new release with these changes included next weekend.

2024-05-05 18:03 UTC, merged