Add "remaining" attribute
rianadon/timer-bar-card pull request #47
Opened 2022-06-06 23:28 UTC by funtastix

For LG Sensors, an initial time and remaining time attribute is provided. Therefore, for correct timing, adding an attribute "remaining" that can specify where to read the exact remaining time makes sense.

2022-06-06 23:29 UTC, funtastix commented
![image](https://user-images.githubusercontent.com/11022970/172265684-083ec9af-df5c-4bd2-bc73-7f9b225c5f63.png)
This is the final result.

2022-06-09 05:47 UTC, rianadon commented
I was hoping I'd never have to support a remaining attribute. It's yet another complication to the card's configuration.

However, I took a look through the LG ThinQ integration to see how easy it would be to add support for a start time or end time value. LG designed their API so all that you get back is time remaining and initial duration, so calculating an accurate and consistent start time would be impossible, especially because they don't even give you seconds remaining!

So I'm willing to merge this.

I'll take a deeper look into the PR and what more documentation this needs later.
However, I just enabled CI and want to mention some things:
1. Ignore HACS Action. I don't know what it's complaining about but I'll probably turn it off for pull requests.
2. This PR as it stands breaks the card with native Home Assistant timers. These native timers are smart in that they don't update their values every second to avoid flooding the system with data. The frontend instead compensates for the lack of updates by adjusting the remaining time with how much time has passed until the sensor changed value. If the time remaining is 5 seconds but was updated 3 seconds ago, the time remaining shown on the frontend is 2 seconds. This code path is no longer executed due to line 55, but I'd be curious if the LG integration behaves correctly if you used the new `remainingAttr` function in [line 57](https://github.com/rianadon/timer-bar-card/blob/51beb0fbd8177cbbef986ced8a5d1bab9645c11f/src/helpers.ts#L57=).

2022-06-23 23:25 UTC, funtastix commented
Did a small refactor and also renamed the attribute internally to make it different from the usage of "remaining" that was already there. Seems like both timers are now working as I would expect:
![image](https://user-images.githubusercontent.com/11022970/175430956-d5715f14-4792-434a-925c-01938794792b.png)

2022-07-07 05:03 UTC, rianadon requested changes
Looks awesome! Thanks for adding the documentation! A few suggestions on naming things but thank you for writing and testing the code!

2022-07-07 05:03 UTC, rianadon commented on src/timer-bar-entity-row.ts
> +    remain_time: { attribute: 'remain_time' },
`remain_time` seems a little lengthy of a name. What do you think of `remainder`?

2022-07-07 05:03 UTC, rianadon commented on src/helpers.ts
> +  const remain_time = durationAttr(hass, stateObj, config.remain_time);
It would be nice to rename this function as it's no longer being used for just duration. Maybe `getAttrFromConfig` or something?

2022-12-21 08:50 UTC, rianadon commented
I'm going to merge this in and make a few more changes. Thank you so much for the pull request!

2022-12-21 08:51 UTC, merged